name: theoyrus_skripsi_face
version: 1.0.0+1
publish_to: none
description: Face Recognition Attendance Mobile Apps
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  camera: ^0.10.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dio_smart_retry: ^1.4.0
  envied: ^0.3.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.7.0
  flutter_smart_dialog: ^4.8.2+4
  form_builder_extra_fields: ^8.3.0
  form_builder_validators: ^8.4.0
  get: 4.6.5
  get_storage: ^2.0.3
  google_mlkit_commons: ^0.2.0
  google_mlkit_face_detection: ^0.5.0
  image: ^3.2.2
  intl: ^0.17.0
  jwt_decode: ^0.3.1
  lazy_load_scrollview: ^1.3.0
  lottie: ^2.2.0
  material_design_icons_flutter: ^6.0.7096
  path_provider: ^2.0.11
  pretty_dio_logger: ^1.1.1
  pull_to_refresh: ^2.0.0
  sentry_flutter: ^6.18.2
  side_navigation: ^1.0.4
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  build_runner: ^2.3.3
  change_app_package_name: ^1.1.0
  envied_generator: ^0.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
